version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      arrow:
        patterns: ["arrow", "arrow-flight"]
        update-types: ["major", "minor", "patch"]
      anise:
        patterns: ["anise", "nalgebra"]
        update-types: ["major", "minor", "patch"]
      minor-and-patch:
        patterns: ["*"]
        exclude-patterns: ["arrow", "arrow-flight", "anise", "nalgebra"]
        update-types: ["minor", "patch"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
