[workspace]
members = [
    "crates/spacetimestamp",
    "crates/soloc-ledger",
    "crates/soloc-server",
]
resolver = "2"

[workspace.package]
license = "Apache-2.0"

[workspace.dependencies]
arrow = "60.0.0"
arrow-flight = "60.0.0"
anise = "0.10.4"
nalgebra = "0.35"
hifitime = "4.2.4"
log = "0.4"

test-log = "0.2.19"
criterion = { version = "0.8", features = ["html_reports"] }
