[package]
name = "soloc-ledger"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
spacetimestamp = { path = "../spacetimestamp" }
anise.workspace = true
nalgebra.workspace = true
hifitime.workspace = true
arrow.workspace = true
log.workspace = true

[dev-dependencies]
test-log.workspace = true
criterion.workspace = true
