[package]
name = "spacetimestamp"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anise.workspace = true
arrow.workspace = true
hifitime.workspace = true
log.workspace = true
nalgebra.workspace = true
sha2 = "0.11"

[dev-dependencies]
test-log.workspace = true
criterion.workspace = true
