[package]
name = "spacetimestamp"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anise = "0.9.4"
arrow = "57.1.0"
hifitime = "4.2.4"
log = "0.4"
nalgebra = "0.34"

[dev-dependencies]
test-log = "0.2.19"
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "spacetimestamp_bench"
harness = false

[[bench]]
name = "topology_bench"
harness = false
