[package]
name = "soloc"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
spacetimestamp = { path = "../spacetimestamp" }
anise = "0.9.4"
nalgebra = "0.34"
hifitime = "4.2.3"
arrow = "59.2.0"
log = "0.4"

[dev-dependencies]
test-log = "0.2.19"
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "ledger_bench"
harness = false
